<div class="flex flex-col gap-6">
    <x-proposal-context :proposal="$this->proposal" :step="$this->step()" /><x-proposal-feedback />
    <form wire:submit="save" class="flex flex-col gap-6"><fieldset class="flex flex-col gap-5" @disabled(!auth()->user()->can('update', $this->proposal))>
        <p><span aria-hidden="true" class="text-error">*</span> indica campo obrigatório. O primeiro ano é calculado pela quantidade e pelo valor unitário. Preencha as projeções dos anos seguintes; deixe vazio ou use zero onde não houver movimentação.</p>
        @foreach(\App\Enums\CashFlowType::cases() as $type)<section class="card bg-base-100" wire:key="cash-type-{{ $type->value }}"><div class="card-body gap-4"><div class="flex flex-wrap items-center justify-between gap-3"><h2 class="card-title">{{ $type->label() }}</h2><button type="button" wire:click="addItem('{{ $type->value }}')" wire:loading.attr="disabled" wire:target="addItem('{{ $type->value }}')" class="btn btn-sm btn-outline"><span wire:loading.remove wire:target="addItem('{{ $type->value }}')">Adicionar item</span><span wire:loading wire:target="addItem('{{ $type->value }}')">Adicionando…</span></button></div>
            @php($typeItems = collect($items)->filter(fn (array $item): bool => ($item['type'] instanceof \App\Enums\CashFlowType ? $item['type']->value : $item['type']) === $type->value))
            @forelse($typeItems as $key => $item)<div wire:key="cash-{{ $key }}" class="flex flex-col gap-3 rounded-lg border border-base-300 p-4">
                <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><x-proposal-field :model="'items.'.$key.'.description'" label="Produto / descrição" :required="true" /><fieldset class="fieldset"><label for="cash-unit-{{ $key }}">Unidade <span aria-hidden="true" class="text-error">*</span></label><x-searchable-select id="cash-unit-{{ $key }}" :model="'items.'.$key.'.unit'" :value="$item['unit']" :options="collect(\App\Enums\PatrimonyUnit::cases())->map(fn ($unit) => ['value' => $unit->value, 'label' => $unit->label()])->all()" placeholder="Selecione" search-placeholder="Pesquisar unidade" /></fieldset><x-proposal-field :model="'items.'.$key.'.quantity'" label="Quantidade" type="number" step="1" :live="true" :required="true" /><x-proposal-field :model="'items.'.$key.'.unit_value'" label="Valor unitário (R$)" type="number" :money="true" :live="true" :required="true" /></div>
                <div class="grid gap-3 sm:grid-cols-3 lg:grid-cols-7"><div class="fieldset"><span>Ano 1 (R$)</span><output class="py-3 font-semibold">{{ number_format(\App\Services\Proposals\ProposalCalculator::itemTotal($item['quantity'], $item['unit_value']), 2, ',', '.') }}</output></div>@for($year = 2; $year <= 7; $year++)<x-proposal-field :model="'items.'.$key.'.year_'.$year" :label="'Ano '.$year.' (R$)'" type="number" :money="true" :live="true" />@endfor</div>
                <button type="button" wire:click="removeItem('{{ $key }}')" class="btn btn-sm btn-ghost text-error self-start">Remover item</button>
            </div>@empty<p class="text-sm text-base-content/60">Nenhum item informado. Use “Adicionar item” para incluir um registro em {{ mb_strtolower($type->label()) }}.</p>@endforelse
        </div></section>@endforeach
    </fieldset><section class="card bg-base-100"><div class="card-body">@include('proposals.cash-summary', ['cashFlow' => $this->summary])</div></section><x-proposal-actions :proposal="$this->proposal" /></form>
</div>
