<div class="flex flex-col gap-6">
    <x-proposal-context :proposal="$this->proposal" :step="$this->step()" /><x-proposal-feedback />
    <form wire:submit="save" class="flex flex-col gap-6">
        <fieldset class="flex flex-col gap-5" @disabled(!auth()->user()->can('update', $this->proposal))>
            <p>Inclua apenas os bens existentes. Categorias sem bens podem ficar vazias. Confira também as dívidas antes de concluir.</p>
            <section class="card bg-base-100"><div class="card-body gap-4"><div class="flex flex-wrap items-center justify-between gap-3"><h2 class="card-title">Levantamento patrimonial</h2><button type="button" wire:click="addItem" class="btn btn-primary">Adicionar item</button></div><div class="grid gap-4 rounded-lg border border-primary/20 bg-base-200/30 p-4 sm:grid-cols-2"><fieldset class="fieldset"><label for="new-item-category">Categoria</label><x-searchable-select id="new-item-category" model="newItem.category" :value="$newItem['category']" :options="collect($categories)->map(fn ($item) => ['value' => $item->value, 'label' => $item->label()])->all()" placeholder="Selecione" search-placeholder="Pesquisar categoria" /></fieldset><x-proposal-field model="newItem.description" label="Especificação" /><fieldset class="fieldset"><label for="new-item-unit">Unidade</label><x-searchable-select id="new-item-unit" model="newItem.unit" :value="$newItem['unit']" :options="collect($units)->map(fn ($item) => ['value' => $item->value, 'label' => $item->label()])->all()" placeholder="Selecione" search-placeholder="Pesquisar unidade" /></fieldset><x-proposal-field model="newItem.quantity" label="Quantidade" type="number" step="0.0001" /><x-proposal-field model="newItem.unit_value" label="Valor unitário (R$)" type="number" :money="true" :live="true" /></div>
                @forelse($items as $key => $item)<div wire:key="patrimony-{{ $key }}" class="grid gap-4 rounded-lg border border-base-300 p-4 sm:grid-cols-2"><fieldset class="fieldset"><label for="item-category-{{ $key }}">Categoria</label><x-searchable-select id="item-category-{{ $key }}" model="items.{{ $key }}.category" :value="$item['category']" :options="collect($categories)->map(fn ($item) => ['value' => $item->value, 'label' => $item->label()])->all()" placeholder="Categoria" search-placeholder="Pesquisar categoria" /></fieldset><x-proposal-field :model="'items.'.$key.'.description'" label="Especificação" /><fieldset class="fieldset"><label for="item-unit-{{ $key }}">Unidade</label><x-searchable-select id="item-unit-{{ $key }}" :model="'items.'.$key.'.unit'" :value="$item['unit']" :options="collect($units)->map(fn ($item) => ['value' => $item->value, 'label' => $item->label()])->all()" placeholder="Unidade" search-placeholder="Pesquisar unidade" /></fieldset><x-proposal-field :model="'items.'.$key.'.quantity'" label="Quantidade" type="number" step="0.0001" :live="true" /><x-proposal-field :model="'items.'.$key.'.unit_value'" label="Valor unitário (R$)" type="number" :money="true" :live="true" /><div class="flex items-end justify-between gap-3 sm:col-span-2"><p class="font-semibold">Total: R$ {{ number_format(\App\Services\Proposals\ProposalCalculator::itemTotal($item['quantity'], $item['unit_value']), 2, ',', '.') }}</p><button type="button" wire:click="removeItem('{{ $key }}')" class="btn btn-sm btn-ghost text-error">Remover</button></div></div>@empty<p>Nenhum item informado.</p>@endforelse
            </div></section>
            <section class="card bg-base-100"><div class="card-body gap-4"><div class="flex justify-between gap-3"><h2 class="card-title">Dívidas agropecuárias</h2><button type="button" wire:click="addDebt" class="btn btn-sm btn-outline">Adicionar dívida</button></div>
                @forelse($debts as $key => $debt)
                    <div wire:key="debt-{{ $key }}" class="grid gap-3 rounded-lg border border-base-300 p-4 sm:grid-cols-2">
                        <div><label for="debt-creditor-{{ $key }}">Quem deve</label><x-searchable-select id="debt-creditor-{{ $key }}" :model="'debts.'.$key.'.creditor'" :value="$debt['creditor']" :options="$this->debtCreditors" placeholder="Selecione beneficiário ou cônjuge" search-placeholder="Buscar devedor pelo nome" /></div><x-proposal-field :model="'debts.'.$key.'.purpose'" label="Finalidade" />
                        <x-proposal-field :model="'debts.'.$key.'.due_date'" label="Vencimento" type="date" /><x-proposal-field :model="'debts.'.$key.'.outstanding_balance'" label="Saldo devedor (R$)" type="number" :money="true" :live="true" />
                        <button type="button" wire:click="removeDebt('{{ $key }}')" class="btn btn-sm btn-ghost text-error justify-self-start">Remover dívida</button>
                    </div>
                @empty<p>Nenhuma dívida informada.</p>@endforelse
            </div></section>
        </fieldset>
        @include('proposals.patrimony-totals', ['totals' => $this->totals])
        <x-proposal-actions :proposal="$this->proposal" />
    </form>
</div>
