server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php;
    charset utf-8;

    resolver 127.0.0.11 valid=10s ipv6=off;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /index.php {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        set  $php_backend app:9000;
        fastcgi_pass $php_backend;
        fastcgi_hide_header X-Powered-By;
    }

    location ~ \.php$ {
        return 404;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
